spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/motion?autoReconnect=true&jdbcCompliantTruncation=false&useSSL=false
    username: motion
    password: motion
    driver-class-name: org.mariadb.jdbc.Driver
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: Asia/Seoul
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    view:      prefix: /WEB-INF/views/
      suffix: .jsp
  messages:
    basename: i18n/exception
    encoding: UTF-8
app:
  jwt:
    secret: motion
    expirationInMs: 3600000
    header: Authorization
    prefix: Bearer

cors:
  allowedOrings: '*'
  
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.go.check.domain
  